### ISSUE TITLE
First release todo's

### ISSUE THREAD

**Issue by stonier** [stonier/ckx_tools#15]
* [x] console -> terminal color
* [x] collapse `initialize_config` and `initialise_ckx_tools_home` in `config.py`: 755f1c1f6
* [x] `catkin config` clarification with default tracks : 2a35386c
* [x] `catkin ws --clean` : 6c4d27fd* [ ] bash completion for the new commands
* [x] `catkin build --install`
* [x] `catkin build` from inside the parallel build directory : 06fc0f14
* [x] `catkin build --install-rosdeps`
* [x] `catkin build --doc`
* [ ] `catkin build --tests`
* [ ] `catkin build --run-tests`
* [ ] `catkin build --strip`
* [ ] docs to match `yujin_make`
* [ ] catkin_tools -> ckx_tools
* [ ] update `.github/ISSUE_TEMPLATE.md`
* [ ] ubuntu cross compiling tutorials
* [ ] ppa deb
